### PR TITLE
Update asn1.js

### PR DESCRIPTION
**Pull request by guybedford**
Thanks for all the help getting these through. Still ironing out the bn.js fork here.

See https://github.com/indutny/asn1.js/pull/32 as well.

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
so this isn't stricly needed except to prevent weird cache issues, but doesn't hurt

**Comment by calvinmetcalf** [comment]
I had to unpublish this as it causes an peer invalid error, ping me when its safe to publish again

**Comment by guybedford** [comment]
The peer dependency conflict will exist so long as bn.js 0.15 is a peer dependency is in the same tree.

The way around this would be to bump the major.

**Comment by calvinmetcalf** [comment]
bump the major where? I thought we were just waiting on indutny/asn1.js#32 to upgrade?

**Comment by guybedford** [comment]
Ahh right, sorry I thought you meant the bn.js 0.15 peer dependency issue was still happening, but of course that's been resolved.

**Pull request merged**
