### PR TITLE
reverting back to minor

### PR DESCRIPTION
**Pull request by mrgurdeep**
the change is breaking. so creating the major release version

### CODE REVIEW

**Comment by mrgurdeep** [comment]
@calvinmetcalf please help and review

**Comment by mrgurdeep** [comment]
#41 will be resolved due to this

**Comment by calvinmetcalf** [comment]
closing this in favor of #41

**Comment by mrgurdeep** [comment]
@calvinmetcalf #41 suggestion is only a work around.

**Pull request closed without merging**
